### ISSUE TITLE
use of deprected qt function

### ISSUE THREAD

**Issue by mathisloge** [arobenko/comms_champion#7]
https://github.com/arobenko/comms_champion/blob/9187a4e39f19767d53e6206ad4bb29ff6a523a11/comms_champion/app/cc_view/src/widget/ProtocolsStackWidget.cpp#L179

should be replaced with item->isSelected() 

[https://doc.qt.io/qt-5/qlistwidget-obsolete.html#isItemSelected](https://doc.qt.io/qt-5/qlistwidget-obsolete.html#isItemSelected)

**Comment by arobenko** [comment]
Thanks. 
I'll fix it in the next upcoming "patch" release. Should be out within a week or so.

**Comment by arobenko** [comment]
The fix has been introduced to "develop" branch, will be merged to master when release is ready

**Comment by arobenko** [comment]
Merged to `master` branch and available since [v2.0.1](https://github.com/arobenko/comms_champion/releases/tag/v2.0.1)
